### ISSUE TITLE
Mbrola Error

### ISSUE THREAD

**Issue by Monal5031** [Monal5031/TextToSpeech-Converter#1]
When I try to run my code it shows 

> this:System property "mbrola.base" is undefined.  Will not use MBROLA voices.Exception in thread "main" 
java.lang.NullPointerException
	at speak.talk(speak.java:45)
	at speak.main(speak.java:67)

tried some suggestions online too but didn't get it right

**Comment by Monal5031** [comment]
It works fine with "kevin16" but not with "kevin8"
